name: Api - Dev Build and Deploy
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build

    - uses: ./
      with:
        file: sample.yml
        outputPath: ${{ github.workspace }}        